/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackpackItem {
  'id' : bigint,
  'weight' : number,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createItem' : ActorMethod<[string, bigint, string, number], BackpackItem>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItem' : ActorMethod<[bigint], BackpackItem>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasBackpack' : ActorMethod<[], boolean>,
  'initializeBackpack' : ActorMethod<[], [] | [boolean]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listItems' : ActorMethod<[], Array<BackpackItem>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateItem' : ActorMethod<
    [bigint, string, bigint, string, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];