/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BackpackItem = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createItem' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
      [BackpackItem],
      [],
    ),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [BackpackItem], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasBackpack' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeBackpack' : IDL.Func([], [IDL.Opt(IDL.Bool)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listItems' : IDL.Func([], [IDL.Vec(BackpackItem)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BackpackItem = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createItem' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
        [BackpackItem],
        [],
      ),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItem' : IDL.Func([IDL.Nat], [BackpackItem], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasBackpack' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeBackpack' : IDL.Func([], [IDL.Opt(IDL.Bool)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listItems' : IDL.Func([], [IDL.Vec(BackpackItem)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };